### ISSUE TITLE
Add native-tls-vendored feature

### ISSUE THREAD

**Issue by T0mstone** [stevepryde/thirtyfour_sync#1]
I need the native-tls-vendored feature of reqwest for cross-compiling.

I propose adding the following to Cargo.toml

```
[features]
native-tls-vendored = ["reqwest/native-tls-vendored"]
```

This is a very small change but I can open a PR if needed

## Possible further action
- Also add this feature to the other thirtyfour crates

**Comment by stevepryde** [comment]
This looks fine. I am happy for you to open a PR. If you do, could you please also add a rustls feature at the same time? These are probably the two most common options.

**Comment by T0mstone** [comment]
Please review my added documentation, I think it could be better
