### ISSUE TITLE
openssl-sys is pulled down by thirtyfour even when using rustls

### ISSUE THREAD

**Issue by 1000teslas** [stevepryde/thirtyfour_sync#6]
Thanks for providing a sync interface to thirtyfour. It's nice to not need to use async for some quick 'n' dirty work. I think it's basically the same as https://github.com/stevepryde/thirtyfour/issues/49, in that the thirtyfour dependency by default pulls in openssl even when the default features are disabled.

**Comment by 1000teslas** [comment]
I've set default-features to false when importing `thirtyfour_sync` in my project, but I still pull in openssl. When I clone the thirtyfour_sync repo and set default-features to false for the dependency thirtyfour, it doesn't pull in openssl.

**Comment by stevepryde** [comment]
Aha, that makes sense. I'll have a look at that tonight.

**Comment by 1000teslas** [comment]
Yup, that fixes it. Thanks.
