### ISSUE TITLE
Q&A Thread

### ISSUE THREAD

**Issue by bcpeinhardt** [stevepryde/thirtyfour_sync#7]
Hey there! 
I'm not sure where else to ask a question about this. I'm learning Selenium Webdriver from resources written in Python and Java and so far the process of finding the appropriate counterpart in Rust in the Docs has been great, but **I can't figure out where the explicit wait is.**  I've looked for WebDriverWait and expected_conditions in the docs and I'm a little lost. Not exactly a maintainer's job but could you point me in the right direction?

**Comment by stevepryde** [comment]
Explicit waits have not been added to the sync version yet. They are not part of the webdriver W3C spec.

For the async version this was previously supported via the `thirtyfour_query` crate. That has recently been merged into the main `thirtyfour` crate.

**Comment by stevepryde** [comment]
FYI I've just published `v0.25.0` for `thirtyfour_sync` which includes the new `ElementQuery` and `ElementWaiter` functionality. See the updated docs for more info. Let me know if this provides the functionality you are looking for.

**Comment by bcpeinhardt** [comment]
This is exactly what I was looking for! Thank you! I'm just working on a personal project so I'll migrate over to asnyc if there are notable slowdowns, but `ElementQuery` and `ElementWaiter` cover more than what I needed. I'm working with a very dynamic site so presence in the dom hasn't been a strict enough requirement for a few cases. The predicates outlined in `ElementQuery` and `ElementWaiter` are really what I was looking for.
