### ISSUE TITLE
Can the thirtyfour package dependency be upgraded to the latest version?

### ISSUE THREAD

**Issue by Ev1lT3rm1nal** [stevepryde/thirtyfour_sync#9]
Well, I am trying to use `set_preferences` on firefox but this feature is only avaliable on version 0.26, and the lastest version of this crate is using 0.25.1

**Comment by stevepryde** [comment]
Sorry, it seems this has fallen behind a little. I'll update it shortly

**Comment by stevepryde** [comment]
Updated to `v0.27.0` (skipped 0.26 because this also adds compatibility / parity with `thirtyfour` v0.27.x)
